return {
	keyCommands = {
		{down = device_commands.BRAKE_AntiSkidAndSpoilerBrake,     up = device_commands.BRAKE_AntiSkidAndSpoilerBrake, value_down = -1, value_up = 0, cockpit_device_id=devices.GEARHOOK, name = _('Anti Skid Spoiler BK Switch Spoiler BK, else OFF'), category = _('Gears, brakes, and hook')},
		{down = device_commands.BRAKE_AntiSkidAndSpoilerBrake,     up = device_commands.BRAKE_AntiSkidAndSpoilerBrake, value_down = 1, value_up = 0, cockpit_device_id=devices.GEARHOOK, name = _('Anti Skid Spoiler BK Switch BOTH, else OFF'), category = _('Gears, brakes, and hook')},
		{down = device_commands.BRAKE_AntiSkidAndSpoilerBrake, 		cockpit_device_id = devices.GEARHOOK, value_down = -1, name = _('Anti Skid Spoiler BK Switch SPOILER BK'), category = { _('Gears, brakes, and hook')}},
		{down = device_commands.BRAKE_AntiSkidAndSpoilerBrake, 		cockpit_device_id = devices.GEARHOOK, value_down = 0, name = _('Anti Skid Spoiler BK Switch OFF'), category = { _('Gears, brakes, and hook')}},
		{down = device_commands.BRAKE_AntiSkidAndSpoilerBrake, 		cockpit_device_id = devices.GEARHOOK, value_down = 1, name = _('Anti Skid Spoiler BK Switch BOTH'), category = { _('Gears, brakes, and hook')}},
		{up=device_commands.BRAKE_ParkingBrake, down=device_commands.BRAKE_ParkingBrake, 	cockpit_device_id=devices.GEARHOOK, value_up=0.0, value_down=1.0,	name=_('Parking brake disabled, else enabled'),category=_('Gears, brakes, and hook')},
		{down = device_commands.BRAKE_ParkingBrake, 		cockpit_device_id = devices.GEARHOOK, value_down = 0, name = _('Parking Brake Handle ON'), category = { _('Gears, brakes, and hook')}},
		{down = device_commands.BRAKE_ParkingBrake, 		cockpit_device_id = devices.GEARHOOK, value_down = 1, name = _('Parking Brake Handle OFF'), category = { _('Gears, brakes, and hook')}},

		{down = device_commands.HYD_ISOL_Switch, cockpit_device_id = devices.HYDRAULICS, value_down = 0, name = _('Hydraulic Isolation Switch On'), category = { _('Gears, brakes, and hook')}},
		{down = device_commands.HYD_ISOL_Switch, cockpit_device_id = devices.HYDRAULICS, value_down = 1, name = _('Hydraulic Isolation Switch Off'), category = { _('Gears, brakes, and hook')}},

		{down = device_commands.GEAR_LaunchBarAbortCover, up = device_commands.GEAR_LaunchBarAbortCover, cockpit_device_id = devices.GEARHOOK, value_down = 1, value_up = -1, name = _('Launch Bar Abort Switch Cover Open else Closed'), category = { _('Gears, brakes, and hook')}},
		{down = device_commands.GEAR_LaunchBarAbort, up = device_commands.GEAR_LaunchBarAbort, cockpit_device_id = devices.GEARHOOK, value_down = 1, value_up = -1, name = _('Launch Bar Abort Switch Abort else Auto'), category = { _('Gears, brakes, and hook')}},

		{down = device_commands.GEAR_DownLockOverride, cockpit_device_id = devices.GEARHOOK, value_down = 1, value_up = 0, name = _('Down Lock Override'), category = { _('Gears, brakes, and hook')}},

		{down = device_commands.PilotOxygenOn, 		cockpit_device_id = devices.COCKPITMECHANICS, value_down = 0, name = _('Pilot Oxygen Off'), category = { _('Left sidewall')}},
		{down = device_commands.PilotOxygenOn, 		cockpit_device_id = devices.COCKPITMECHANICS, value_down = 1, name = _('Pilot Oxygen On'), category = { _('Left sidewall')}},
		{down = device_commands.PilotOxygenOn,     up = device_commands.PilotOxygenOn, value_down = 1, value_up = 0, cockpit_device_id = devices.COCKPITMECHANICS, name = _('Pilot Oxygen ON, else OFF'), category = _('Left sidewall')},

		{down = device_commands.ARA63_Power_Switch, cockpit_device_id = devices.ILS, value_down = 0, name = _('ILS Power Switch Off'), category = { _('ILS')}},
		{down = device_commands.ARA63_Power_Switch, cockpit_device_id = devices.ILS, value_down = 1, name = _('ILS Power Switch On'), category = { _('ILS')}},
		{down = device_commands.ARA63_BIT_Btn, up = device_commands.ARA63_BIT_Btn, cockpit_device_id = devices.ILS, value_down = 1, value_up = 0, name = _('ILS BIT Button'), category = { _('ILS')}},
		{down = device_commands.ARA63_Chnl_Knob, cockpit_device_id = devices.ILS, value_down = 0, name = _('ILS Channel Knob 1'), category = { _('ILS')}},
		{down = device_commands.ARA63_Chnl_Knob, cockpit_device_id = devices.ILS, value_down = 1/19, name = _('ILS Channel Knob 2'), category = { _('ILS')}},

		{down = device_commands.AirSourceRam, 		cockpit_device_id = devices.COCKPITMECHANICS, value_down = 1, name = _('Air Source Ram'), category = { _('Cockpit Mechanics')}},
		{down = device_commands.AirSourceOff, 		cockpit_device_id = devices.COCKPITMECHANICS, value_down = 1, name = _('Air Source Off'), category = { _('Cockpit Mechanics')}},
		{down = device_commands.AirSourceLEng, 		cockpit_device_id = devices.COCKPITMECHANICS, value_down = 1, name = _('Air Source Left Engine'), category = { _('Cockpit Mechanics')}},
		{down = device_commands.AirSourceREng, 		cockpit_device_id = devices.COCKPITMECHANICS, value_down = 1, name = _('Air Source Right Engine'), category = { _('Cockpit Mechanics')}},
		{down = device_commands.AirSourceBoth, 		cockpit_device_id = devices.COCKPITMECHANICS, value_down = 1, name = _('Air Source Both Engines'), category = { _('Cockpit Mechanics')}},

		{down = device_commands.WindShield_Air, 		cockpit_device_id = devices.COCKPITMECHANICS, value_down = -1, name = _('Wind Shield Air OFF'), category = { _('External Environment')}},
		{down = device_commands.WindShield_Air, 		cockpit_device_id = devices.COCKPITMECHANICS, value_down = 0, name = _('Wind Shield Air AIR'), category = { _('External Environment')}},
		{down = device_commands.WindShield_Air, 		cockpit_device_id = devices.COCKPITMECHANICS, value_down = 1, name = _('Wind Shield Air RAIN'), category = { _('External Environment')}},

		{down = device_commands.CabinPressureDump, 		cockpit_device_id = devices.COCKPITMECHANICS, value_down = 0, name = _('Cabin Pressure Dump NORM'), category = { _('Cockpit Mechanics')}},
		{down = device_commands.CabinPressureDump, 		cockpit_device_id = devices.COCKPITMECHANICS, value_down = 1, name = _('Cabin Pressure Dump DUMP'), category = { _('Cockpit Mechanics')}},

		{down = device_commands.TempAutoMan, 		cockpit_device_id = devices.COCKPITMECHANICS, value_down = 0, name = _('Temp Auto / Man AUTO'), category = { _('Cockpit Mechanics')}},
		{down = device_commands.TempAutoMan, 		cockpit_device_id = devices.COCKPITMECHANICS, value_down = 1, name = _('Temp Auto / Man MAN'), category = { _('Cockpit Mechanics')}},
		{down = device_commands.RamAir, 		cockpit_device_id = devices.COCKPITMECHANICS, value_down = 0, name = _('Ram Air DECR'), category = { _('Cockpit Mechanics')}},
		{down = device_commands.RamAir, 		cockpit_device_id = devices.COCKPITMECHANICS, value_down = 1, name = _('Ram Air INCR'), category = { _('Cockpit Mechanics')}},

		{down = device_commands.HYD_EMERG_FLT_Switch, 		cockpit_device_id = devices.HYDRAULICS, value_down = -1, name = _('Hydraulic Emergency Flight Control Switch Auto'), category = { _('Cockpit Mechanics')}},
		{down = device_commands.HYD_EMERG_FLT_Switch, 		cockpit_device_id = devices.HYDRAULICS, value_down = 0, name = _('Hydraulic Emergency Flight Control Switch Low'), category = { _('Cockpit Mechanics')}},
		{down = device_commands.HYD_EMERG_FLT_Switch, 		cockpit_device_id = devices.HYDRAULICS, value_down = 1, name = _('Hydraulic Emergency Flight Control Switch High'), category = { _('Cockpit Mechanics')}},
		{down = device_commands.HYD_EMERG_FLT_SwitchCover, 		cockpit_device_id = devices.HYDRAULICS, value_down = 0, name = _('Hydraulic Emergency Flight Control Switch Cover Close'), category = { _('Cockpit Mechanics')}},
		{down = device_commands.HYD_EMERG_FLT_SwitchCover, 		cockpit_device_id = devices.HYDRAULICS, value_down = 1, name = _('Hydraulic Emergency Flight Control Switch Cover Open'), category = { _('Cockpit Mechanics')}},

		{down = device_commands.BIT_Selector, cockpit_device_id = devices.BITPANEL, value_down = 0, name = _('Master Test Selector Position 1'), category = { _('Master Test Selector')}},
		{down = device_commands.BIT_Selector, cockpit_device_id = devices.BITPANEL, value_down = 1/11, name = _('Master Test Selector Position 2'), category = { _('Master Test Selector')}},
		{down = device_commands.BIT_SelectorPush, up = device_commands.BIT_SelectorPush, cockpit_device_id = devices.BITPANEL, value_down = 1, value_up = 0, name = _('Master Test Selector Pull'), category = { _('Master Test Selector')}},

		{down = device_commands.WINGSWEEP_EmergencySweepCover, 		cockpit_device_id = devices.WINGSWEEP, value_down = 0, name = _('Emergency Wing Sweep Handle Cover CLOSE'), category = { _('Throttle')}},
		{down = device_commands.WINGSWEEP_EmergencySweepCover, 		cockpit_device_id = devices.WINGSWEEP, value_down = 1, name = _('Emergency Wing Sweep Handle Cover OPEN'), category = { _('Throttle')}},
		{down = device_commands.WINGSWEEP_EmergencySweepCover,     up = device_commands.WINGSWEEP_EmergencySweepCover, value_down = 1, value_up = 0, cockpit_device_id = devices.WINGSWEEP, name = _('Emergency Wing Sweep Handle Cover OPEN else CLOSED'), category = _('Throttle')},
		{down = device_commands.WINGSWEEP_EmergencySweepCover,     up = device_commands.WINGSWEEP_EmergencySweepCover, value_down = 0, value_up = 1, cockpit_device_id = devices.WINGSWEEP, name = _('Emergency Wing Sweep Handle Cover CLOSED else OPEN'), category = _('Throttle')},
		{down = device_commands.WINGSWEEP_EmergencyLeverExtended,     up=device_commands.WINGSWEEP_EmergencyLeverExtended, cockpit_device_id=devices.WINGSWEEP, value_down = 0.3, value_up = 1.0, name=_('Emergency Wing Sweep Lever Toggle'), category=_('Throttle')},

		{down = device_commands.ENGINE_Throttle_Mode, 		cockpit_device_id = devices.ENGINE, value_down = -1, name = _('Throttle Mode MAN'), category = { _('Throttle')}},
		{down = device_commands.ENGINE_Throttle_Mode, 		cockpit_device_id = devices.ENGINE, value_down = 0, name = _('Throttle Mode BOOST'), category = { _('Throttle')}},
		{down = device_commands.ENGINE_Throttle_Mode, 		cockpit_device_id = devices.ENGINE, value_down = 1, name = _('Throttle Mode AUTO'), category = { _('Throttle')}},
		{down = device_commands.ENGINE_Throttle_Mode,     up = device_commands.ENGINE_Throttle_Mode, value_down = -1, value_up = 0, cockpit_device_id = devices.ENGINE, name = _('Throttle Mode MAN else BOOST'), category = _('Throttle')},
		{down = device_commands.ENGINE_Throttle_Mode,     up = device_commands.ENGINE_Throttle_Mode, value_down = 1, value_up = 0, cockpit_device_id = devices.ENGINE, name = _('Throttle Mode AUTO else BOOST'), category = _('Throttle')},

		{down = device_commands.ENGINE_Throttle_Temp, cockpit_device_id = devices.ENGINE, value_down = -1, name = _('Throttle Temp COLD'), category = { _('Throttle')}},
		{down = device_commands.ENGINE_Throttle_Temp, up = device_commands.ENGINE_Throttle_Temp, cockpit_device_id = devices.ENGINE, value_down = -1, value_up = 0, name = _('Throttle Temp COLD else NORM'), category = { _('Throttle')}},
		{down = device_commands.ENGINE_Throttle_Temp, cockpit_device_id = devices.ENGINE, value_down = 0, name = _('Throttle Temp NORM'), category = { _('Throttle')}},
		{down = device_commands.ENGINE_Throttle_Temp, cockpit_device_id = devices.ENGINE, value_down = 1, name = _('Throttle Temp HOT'), category = { _('Throttle')}},
		{down = device_commands.ENGINE_Throttle_Temp, up = device_commands.ENGINE_Throttle_Temp, cockpit_device_id = devices.ENGINE, value_down = 1, value_up = 0, name = _('Throttle Temp HOT else NORM'), category = { _('Throttle')}},

		{down = device_commands.ENGINE_Asym_LimiterCover, 		cockpit_device_id = devices.ENGINE, value_down = 0, name = _('Asymmetric Thrust Limiter Cover CLOSE'), category = { _('Engine Control Panel')}},
		{down = device_commands.ENGINE_Asym_LimiterCover, 		cockpit_device_id = devices.ENGINE, value_down = 1, name = _('Asymmetric Thrust Limiter Cover OPEN'), category = { _('Engine Control Panel')}},
		{down = device_commands.ENGINE_Asym_LimiterCover,     up = device_commands.ENGINE_Asym_LimiterCover, value_down = 1, value_up = 0, cockpit_device_id = devices.ENGINE, name = _('Asymmetric Thrust Limiter Cover OPEN else CLOSED'), category = _('Engine Control Panel')},
		{down = device_commands.ENGINE_Asym_Limiter, 		cockpit_device_id = devices.ENGINE, value_down = 0, name = _('Asymmetric Thrust Limiter ON'), category = { _('Engine Control Panel')}},
		{down = device_commands.ENGINE_Asym_Limiter, 		cockpit_device_id = devices.ENGINE, value_down = 1, name = _('Asymmetric Thrust Limiter OFF'), category = { _('Engine Control Panel')}},
		{down = device_commands.ENGINE_Asym_Limiter,     up = device_commands.ENGINE_Asym_Limiter, value_down = 1, value_up = 0, cockpit_device_id = devices.ENGINE, name = _('Asymmetric Thrust Limiter OFF else ON'), category = _('Engine Control Panel')},

		{down = device_commands.INLET_RAMPS_LeftSwitch,	cockpit_device_id = devices.AICS, value_down = 0, name = _('Stow Inlet Ramps Left Switch AUTO'), category = { _('Engine Control Panel')}},
		{down = device_commands.INLET_RAMPS_LeftSwitch,	cockpit_device_id = devices.AICS, value_down = 1, name = _('Stow Inlet Ramps Left Switch STOW'), category = { _('Engine Control Panel')}},
		{down = device_commands.INLET_RAMPS_LeftSwitch,	up = device_commands.INLET_RAMPS_LeftSwitch, cockpit_device_id = devices.AICS, value_down = 1, value_up = 0, name = _('Stow Inlet Ramps Left Switch STOW else AUTO'), category = { _('Engine Control Panel')}},
		{down = device_commands.INLET_RAMPS_LeftSwitch,	up = device_commands.INLET_RAMPS_LeftSwitch, cockpit_device_id = devices.AICS, value_down = 0, value_up = 1, name = _('Stow Inlet Ramps Left Switch AUTO else STOW'), category = { _('Engine Control Panel')}},
		{down = device_commands.INLET_RAMPS_RightSwitch, cockpit_device_id = devices.AICS, value_down = 0, name = _('Stow Inlet Ramps Right Switch AUTO'), category = { _('Engine Control Panel')}},
		{down = device_commands.INLET_RAMPS_RightSwitch, cockpit_device_id = devices.AICS, value_down = 1, name = _('Stow Inlet Ramps Right Switch STOW'), category = { _('Engine Control Panel')}},
		{down = device_commands.INLET_RAMPS_RightSwitch, up = device_commands.INLET_RAMPS_RightSwitch, cockpit_device_id = devices.AICS, value_down = 0, value_up = 1, name = _('Stow Inlet Ramps Right Switch AUTO else STOW'), category = { _('Engine Control Panel')}},
		{down = device_commands.INLET_RAMPS_RightSwitch, up = device_commands.INLET_RAMPS_RightSwitch, cockpit_device_id = devices.AICS, value_down = 1, value_up = 0, name = _('Stow Inlet Ramps Right Switch STOW else AUTO'), category = { _('Engine Control Panel')}},

		{down = device_commands.ENGINE_Air_Start, cockpit_device_id = devices.ENGINE, value_down = 0, name = _('Engine Airstart NORM'), category = { _('Engine Control Panel')}},
		{down = device_commands.ENGINE_Air_Start, cockpit_device_id = devices.ENGINE, value_down = 1, name = _('Engine Airstart ON'), category = { _('Engine Control Panel')}},
		{down = device_commands.ENGINE_Air_Start, up = device_commands.ENGINE_Air_Start, cockpit_device_id = devices.ENGINE, value_down = 1, value_up = 0, name = _('Engine Airstart ON else NORM'), category = { _('Engine Control Panel')}},

		{down = device_commands.ENGINE_Crank, 			cockpit_device_id = devices.ENGINE, value_down = 0, name = _('Crank Engine MIDDLE'), category = { _('Engine Control Panel')}},
		{down = device_commands.ENGINE_Left_Mode, 		cockpit_device_id = devices.ENGINE, value_down = 0, name = _('Left Engine Mode PRI'), category = { _('Engine Control Panel')}},
		{down = device_commands.ENGINE_Left_Mode, 		cockpit_device_id = devices.ENGINE, value_down = 1, name = _('Left Engine Mode SEC'), category = { _('Engine Control Panel')}},
		{down = device_commands.ENGINE_Left_Mode, up = device_commands.ENGINE_Left_Mode, cockpit_device_id = devices.ENGINE, value_down = 1, value_up = 0, name = _('Left Engine Mode SEC else PRI'), category = { _('Engine Control Panel')}},
		{down = device_commands.ENGINE_Right_Mode, 		cockpit_device_id = devices.ENGINE, value_down = 0, name = _('Right Engine Mode PRI'), category = { _('Engine Control Panel')}},
		{down = device_commands.ENGINE_Right_Mode, 		cockpit_device_id = devices.ENGINE, value_down = 1, name = _('Right Engine Mode SEC'), category = { _('Engine Control Panel')}},
		{down = device_commands.ENGINE_Right_Mode, up = device_commands.ENGINE_Right_Mode, cockpit_device_id = devices.ENGINE, value_down = 1, value_up = 0, name = _('Right Engine Mode SEC else PRI'), category = { _('Engine Control Panel')}},

		{cockpit_device_id=devices.ENGINE, down = device_commands.THROTTLE_Left_Throttle_CutOff , up = device_commands.THROTTLE_Left_Throttle_CutOff, value_down = 0,  name = _('Left Engine Cutoff ON'), category = _('Engine')},
		{cockpit_device_id=devices.ENGINE, down = device_commands.THROTTLE_Left_Throttle_CutOff , up = device_commands.THROTTLE_Left_Throttle_CutOff, value_down = 1,  name = _('Left Engine Cutoff OFF'), category = _('Engine')},
		{cockpit_device_id=devices.ENGINE, down = device_commands.THROTTLE_Right_Throttle_CutOff, up = device_commands.THROTTLE_Right_Throttle_CutOff, value_down = 0, name = _('Right Engine Cutoff ON'), category = _('Engine')},
		{cockpit_device_id=devices.ENGINE, down = device_commands.THROTTLE_Right_Throttle_CutOff, up = device_commands.THROTTLE_Right_Throttle_CutOff, value_down = 1, name = _('Right Engine Cutoff OFF'), category = _('Engine')},

		{down = device_commands.ELEC_MASTER_GEN_LeftSwitch, 		cockpit_device_id = devices.ELECTRICS, value_down = -1, name = _('Left Generator Switch TEST'), category = { _('Electrical')}},
		{down = device_commands.ELEC_MASTER_GEN_LeftSwitch, 		cockpit_device_id = devices.ELECTRICS, value_down = 0, name = _('Left Generator Switch OFF/RESET'), category = { _('Electrical')}},
		{down = device_commands.ELEC_MASTER_GEN_LeftSwitch, 		cockpit_device_id = devices.ELECTRICS, value_down = 1, name = _('Left Generator Switch NORM'), category = { _('Electrical')}},
		{down = device_commands.ELEC_MASTER_GEN_RightSwitch, 		cockpit_device_id = devices.ELECTRICS, value_down = -1, name = _('Right Generator Switch TEST'), category = { _('Electrical')}},
		{down = device_commands.ELEC_MASTER_GEN_RightSwitch, 		cockpit_device_id = devices.ELECTRICS, value_down = 0, name = _('Right Generator Switch OFF/RESET'), category = { _('Electrical')}},
		{down = device_commands.ELEC_MASTER_GEN_RightSwitch, 		cockpit_device_id = devices.ELECTRICS, value_down = 1, name = _('Right Generator Switch NORM'), category = { _('Electrical')}},
		{down = device_commands.ELEC_EMERG_GEN_SwitchCover, 		cockpit_device_id = devices.ELECTRICS, value_down = 0, name = _('Emergency Generator Switch Cover CLOSE'), category = { _('Electrical')}},
		{down = device_commands.ELEC_EMERG_GEN_SwitchCover, 		cockpit_device_id = devices.ELECTRICS, value_down = 1, name = _('Emergency Generator Switch Cover OPEN'), category = { _('Electrical')}},
		{down = device_commands.ELEC_EMERG_GEN_Switch, 		cockpit_device_id = devices.ELECTRICS, value_down = 0, name = _('Emergency Generator Switch NORM'), category = { _('Electrical')}},
		{down = device_commands.ELEC_EMERG_GEN_Switch, 		cockpit_device_id = devices.ELECTRICS, value_down = 1, name = _('Emergency Generator Switch OFF/RESET'), category = { _('Electrical')}},

		{down = device_commands.ENGINE_Probe_Anti_Ice, 		cockpit_device_id = devices.ENGINE, value_down = -1, name = _('Eng/Probe Anti Ice OFF'), category = { _('External Environment')}},
		{down = device_commands.ENGINE_Probe_Anti_Ice, 		cockpit_device_id = devices.ENGINE, value_down = 0, name = _('Eng/Probe Anti Ice AUTO'), category = { _('External Environment')}},
		{down = device_commands.ENGINE_Probe_Anti_Ice, 		cockpit_device_id = devices.ENGINE, value_down = 1, name = _('Eng/Probe Anti Ice ORIDE'), category = { _('External Environment')}},
		{down = device_commands.ENGINE_Probe_Anti_Ice,     up = device_commands.ENGINE_Probe_Anti_Ice, value_down = -1, value_up = 0, cockpit_device_id = devices.ENGINE, name = _('Eng/Probe Anti Ice OFF, else AUTO'), category = _('External Environment')},
		{down = device_commands.ENGINE_Probe_Anti_Ice,     up = device_commands.ENGINE_Probe_Anti_Ice, value_down = 1, value_up = 0, cockpit_device_id = devices.ENGINE, name = _('Eng/Probe Anti Ice ORIDE, else AUTO'), category = _('External Environment')},

		{down = device_commands.HYD_TRANSFER_PUMP_Switch, 		cockpit_device_id = devices.HYDRAULICS, value_down = 0, name = _('Hydraulic Transfer Pump Switch NORMAL'), category = { _('Right Sidewall')}},
		{down = device_commands.HYD_TRANSFER_PUMP_Switch, 		cockpit_device_id = devices.HYDRAULICS, value_down = 1, name = _('Hydraulic Transfer Pump Switch SHUTOFF'), category = { _('Right Sidewall')}},
		{down = device_commands.HYD_TRANSFER_PUMP_Switch,     up = device_commands.HYD_TRANSFER_PUMP_Switch, value_down = 1, value_up = 0, cockpit_device_id = devices.HYDRAULICS, name = _('Hydraulic Transfer Pump Switch SHUTOFF else NORMAL'), category = _('Right Sidewall')},
		{down = device_commands.HYD_TRANSFER_PUMP_SwitchCover, 		cockpit_device_id = devices.HYDRAULICS, value_down = 0, name = _('Hydraulic Transfer Pump Switch Cover CLOSE'), category = { _('Right Sidewall')}},
		{down = device_commands.HYD_TRANSFER_PUMP_SwitchCover, 		cockpit_device_id = devices.HYDRAULICS, value_down = 1, name = _('Hydraulic Transfer Pump Switch Cover OPEN'), category = { _('Right Sidewall')}},
		{down = device_commands.HYD_TRANSFER_PUMP_SwitchCover,     up = device_commands.HYD_TRANSFER_PUMP_SwitchCover, value_down = 1, value_up = 0, cockpit_device_id = devices.HYDRAULICS, name = _('Hydraulic Transfer Pump Switch Cover OPEN else CLOSE'), category = _('Right Sidewall')},

		{down = device_commands.TACAN_Mode_Norm_Inv_Pilot, 		cockpit_device_id = devices.TACAN, value_down = 0, name = _('TACAN Mode Inverse'), category = { _('TACAN')}},
		{down = device_commands.TACAN_Mode_Norm_Inv_Pilot, 		cockpit_device_id = devices.TACAN, value_down = 1, name = _('TACAN Mode Normal'), category = { _('TACAN')}},

		{down = device_commands.FUELSYSTEM_Fuel_Feed_Cover, 		cockpit_device_id = devices.FUELSYSTEM, value_down = 0, name = _('Fuel Feed Cover CLOSE'), category = { _('Fuelsystem Control Panel')}},
		{down = device_commands.FUELSYSTEM_Fuel_Feed_Cover, 		cockpit_device_id = devices.FUELSYSTEM, value_down = 1, name = _('Fuel Feed Cover OPEN'), category = { _('Fuelsystem Control Panel')}},
		{down = device_commands.FUELSYSTEM_Fuel_Feed_Cover,     up = device_commands.FUELSYSTEM_Fuel_Feed_Cover, value_down = 1, value_up = 0, cockpit_device_id = devices.FUELSYSTEM, name = _('Fuel Feed Cover OPEN else CLOSE'), category = _('Fuelsystem Control Panel')},
		{down = device_commands.FUELSYSTEM_Fuel_Feed, 		cockpit_device_id = devices.FUELSYSTEM, value_down = -1, name = _('Fuel Feed AFT'), category = { _('Fuelsystem Control Panel')}},
		{down = device_commands.FUELSYSTEM_Fuel_Feed, 		cockpit_device_id = devices.FUELSYSTEM, value_down = 0, name = _('Fuel Feed NORM'), category = { _('Fuelsystem Control Panel')}},
		{down = device_commands.FUELSYSTEM_Fuel_Feed, 		cockpit_device_id = devices.FUELSYSTEM, value_down = 1, name = _('Fuel Feed FWD'), category = { _('Fuelsystem Control Panel')}},
		{down = device_commands.FUELSYSTEM_Fuel_Feed,     up = device_commands.FUELSYSTEM_Fuel_Feed, value_down = 1, value_up = 0, cockpit_device_id = devices.FUELSYSTEM, name = _('Fuel Feed FWD else NORM'), category = _('Fuelsystem Control Panel')},
		{down = device_commands.FUELSYSTEM_Fuel_Feed,     up = device_commands.FUELSYSTEM_Fuel_Feed, value_down = -1, value_up = 0, cockpit_device_id = devices.FUELSYSTEM, name = _('Fuel Feed AFT else NORM'), category = _('Fuelsystem Control Panel')},

		{down = device_commands.HUD_ShowHide, 		cockpit_device_id = devices.COCKPITMECHANICS, value_down = 1, name = _('HUD camera Hide'), category = { _('ACM Panel')}},
		{down = device_commands.HUD_ShowHide, 		cockpit_device_id = devices.COCKPITMECHANICS, value_down = 0, name = _('HUD camera Show'), category = { _('ACM Panel')}},

		{down = device_commands.FUELSYSTEM_Shutoff_R, cockpit_device_id = devices.FUELSYSTEM, value_down = 0, name = _('Fuel Shutoff Right On'), category = { _('ACM Panel')}},
		{down = device_commands.FUELSYSTEM_Shutoff_R, cockpit_device_id = devices.FUELSYSTEM, value_down = 1, name = _('Fuel Shutoff Right Off'), category = { _('ACM Panel')}},
		{down = device_commands.FUELSYSTEM_Shutoff_R, up = device_commands.FUELSYSTEM_Shutoff_R, value_down = 1, value_up = 0, cockpit_device_id = devices.FUELSYSTEM, name = _('Fuel Shutoff Right On else Off'), category = _('ACM Panel')},

		{down = device_commands.FUELSYSTEM_Shutoff_L, cockpit_device_id = devices.FUELSYSTEM, value_down = 0, name = _('Fuel Shutoff Left On'), category = { _('ACM Panel')}},
		{down = device_commands.FUELSYSTEM_Shutoff_L, cockpit_device_id = devices.FUELSYSTEM, value_down = 1, name = _('Fuel Shutoff Left Off'), category = { _('ACM Panel')}},
		{down = device_commands.FUELSYSTEM_Shutoff_L, up = device_commands.FUELSYSTEM_Shutoff_L, value_down = 1, value_up = 0, cockpit_device_id = devices.FUELSYSTEM, name = _('Fuel Shutoff Left On else Off'), category = _('ACM Panel')},

		{pressed = device_commands.CANOPY_Open, cockpit_device_id=devices.COCKPITMECHANICS, value_pressed = 1, name = _('Canopy Open'), category = _('Cockpit Mechanics')},
		{pressed = device_commands.CANOPY_Open, cockpit_device_id=devices.COCKPITMECHANICS, value_pressed = -1, name = _('Canopy Close'), category = _('Cockpit Mechanics')},
		{down = device_commands.CANOPY_Drop, up = device_commands.CANOPY_Drop, value_down = 1, value_up = 0, cockpit_device_id = devices.COCKPITMECHANICS, name = _('Canopy Jettison'), category = _('Cockpit Mechanics')},

		{down = device_commands.ALTIMETER_Mode, cockpit_device_id = devices.BAROALTIMETER, value_down = -1, name = _('Altimeter Mode Switch Standby'), category = { _('Instrument Panel')}},
		{down = device_commands.ALTIMETER_Mode, cockpit_device_id = devices.BAROALTIMETER, value_down = 0, name = _('Altimeter Mode Switch Neutral'), category = { _('Instrument Panel')}},
		{down = device_commands.ALTIMETER_Mode, cockpit_device_id = devices.BAROALTIMETER, value_down = 1, name = _('Altimeter Mode Switch Reset'), category = { _('Instrument Panel')}},
		{down = device_commands.ALTIMETER_Mode, up = device_commands.ALTIMETER_Mode, cockpit_device_id = devices.BAROALTIMETER, value_down = 1, value_up = 0, name = _('Altimeter Mode Switch Reset, else Neutral'), category = { _('Instrument Panel')}},

		{pressed=device_commands.ALTIMETER_Knob, cockpit_device_id=devices.BAROALTIMETER, value_pressed=0.1, name=_('Altimeter Knob Increase'), category=_('Instrument Panel')},
		{pressed=device_commands.ALTIMETER_Knob, cockpit_device_id=devices.BAROALTIMETER, value_pressed=-0.1, name=_('Altimeter Knob Decrease'), category=_('Instrument Panel')},

		{pressed=device_commands.RADARALT_Knob, cockpit_device_id=devices.RADARALTIMETER, value_pressed=0.01, name=_('Radar Altimeter Knob Increase'), category=_('Instrument Panel')},
		{pressed=device_commands.RADARALT_Knob, cockpit_device_id=devices.RADARALTIMETER, value_pressed=-0.01, name=_('Radar Altimeter Knob Decrease'), category=_('Instrument Panel')},
		{down=device_commands.RADARALT_Test, up=device_commands.RADARALT_Test, cockpit_device_id=devices.RADARALTIMETER, value_down=1, value_up=0, name = _('Radar Altimeter Knob Push'), category = _('Instrument Panel')},

		{pressed=device_commands.AIRSPEED_Knob, cockpit_device_id=devices.MACHANDAIRSPEED, value_pressed=0.02, name=_('Airspeed Indicator Knob Increase'), category=_('Instrument Panel')},
		{pressed=device_commands.AIRSPEED_Knob, cockpit_device_id=devices.MACHANDAIRSPEED, value_pressed=-0.02, name=_('Airspeed Indicator Knob Decrease'), category=_('Instrument Panel')},
		{down=device_commands.AIRSPD_KnobPush, up=device_commands.AIRSPD_KnobPush, cockpit_device_id=devices.MACHANDAIRSPEED, value_down=1, value_up=0, name = _('Airspeed Indicator Knob Push'), category = _('Instrument Panel')},

		{pressed=device_commands.STDBYADI_trim, cockpit_device_id=devices.STDBYAI, value_pressed=0.02, name=_('Standby ADI Knob Increase'), category=_('Instrument Panel')},
		{pressed=device_commands.STDBYADI_trim, cockpit_device_id=devices.STDBYAI, value_pressed=-0.02,  name=_('Standby ADI Knob Decrease'), category=_('Instrument Panel')},
		{down=device_commands.STDBYADI_uncage, up=device_commands.STDBYADI_uncage, cockpit_device_id=devices.STDBYAI, value_down=1, value_up=0, name = _('Standby ADI Knob Cage'), category = _('Instrument Panel')},

		{pressed=device_commands.FUELSYSTEM_Bingo_Knob, cockpit_device_id=devices.FUELSYSTEM, value_pressed=0.05, name=_('Bingo Fuel Knob Increase'), category=_('Instrument Panel')},
		{pressed=device_commands.FUELSYSTEM_Bingo_Knob, cockpit_device_id=devices.FUELSYSTEM, value_pressed=-0.05,  name=_('Bingo Fuel Knob Decrease'), category=_('Instrument Panel')},
		{down=device_commands.ACCEL_Reset, up=device_commands.ACCEL_Reset, cockpit_device_id=devices.ACCELEROMETER, value_down=1, value_up=0, name = _('Accelerometer Reset'), category = _('Instrument Panel')},
		{down=device_commands.CLOCK_Timer, up=device_commands.CLOCK_Timer, cockpit_device_id=devices.CLOCK, value_down=1, value_up=0, name = _('Clock Push'), category = _('Instrument Panel')},

		{down=device_commands.VDIG_HUD_trim, cockpit_device_id=devices.HUD, value_down=1.5, name=_('HUD Trim Increase'), category=_('VDI')},
		{down=device_commands.VDIG_HUD_trim, cockpit_device_id=devices.HUD, value_down=0.5, name=_('HUD Trim Decrease'), category=_('VDI')},
		{down=device_commands.VDIG_VSDI_trim, cockpit_device_id=devices.VDI, value_down=1.0, name=_('VSDI Screen Trim Increase'), category=_('VDI')}, 
		{down=device_commands.VDIG_VSDI_trim, cockpit_device_id=devices.VDI, value_down=0.5, name=_('VSDI Screen Trim Decrease'), category=_('VDI')}, 
		{down=device_commands.VDIG_VDI_contrast, cockpit_device_id=devices.VDI, value_down=1.0, name=_('VDI Screen Contrast Increase'), category=_('VDI')},
		{down=device_commands.VDIG_VDI_contrast, cockpit_device_id=devices.VDI, value_down=0.5, name=_('VDI Screen Contrast Decrease'), category=_('VDI')},
		{down=device_commands.VDIG_VSDI_bright, cockpit_device_id=devices.VDI, value_down=1.0,  name=_('VDI Screen Brightness Increase'), category=_('VDI')},
		{down=device_commands.VDIG_VSDI_bright, cockpit_device_id=devices.VDI, value_down=0.5, name=_('VDI Screen Brightness Decrease'), category=_('VDI')},
		{down=device_commands.VDIG_HUD_bright, cockpit_device_id=devices.HUD, value_down=1.0, name=_('HUD Brightness Increase'), category=_('VDI')},
		{down=device_commands.VDIG_HUD_bright, cockpit_device_id=devices.HUD, value_down=0.5, name=_('HUD Brightness Decrease'), category=_('VDI')},

		{ down=device_commands.VDIG_VDI_handle,up=device_commands.VDIG_VDI_handle, cockpit_device_id=devices.HUD, value_down=0, value_up=1, name = _('HUD Filter OFF else ON'), category = _('VDI')},
		{ down=device_commands.VDIG_VDI_handle,up=device_commands.VDIG_VDI_handle, cockpit_device_id=devices.HUD, value_down=0, name = _('HUD Filter OFF'), category = _('VDI')},
		{ down=device_commands.VDIG_VDI_handle,up=device_commands.VDIG_VDI_handle, cockpit_device_id=devices.HUD, value_down=1, name = _('HUD Filter ON'), category = _('VDI')},
		{ down=device_commands.VDIG_VDI_filter,up=device_commands.VDIG_VDI_filter, cockpit_device_id=devices.VDI, value_down=1, value_up=1, name = _('VDI Filter Momentary OFF/ON'), category = _('VDI')},
		{ down=device_commands.VDIG_VDI_filter,up=device_commands.VDIG_VDI_filter, cockpit_device_id=devices.VDI, value_down=1, name = _('VDI Filter Toggle OFF/ON'), category = _('VDI')},

		{pressed=device_commands.HSD_Knob_Course, up=device_commands.HSD_Knob_Course, cockpit_device_id=devices.HSD, value_pressed=0.01, value_up=0.0, name=_('Course Knob [coarse] - CW'), category=_('HSD')}, 
		{pressed=device_commands.HSD_Knob_Course, up=device_commands.HSD_Knob_Course, cockpit_device_id=devices.HSD, value_pressed=-0.01, value_up=0.0, name=_('Course Knob [coarse] - CCW'), category=_('HSD')}, 
		{pressed=device_commands.HSD_Knob_Heading, up=device_commands.HSD_Knob_Heading, cockpit_device_id=devices.HSD, value_pressed=0.01, value_up=0.0, name=_('Heading Knob [coarse] - CW'), category=_('HSD')}, 
		{pressed=device_commands.HSD_Knob_Heading, up=device_commands.HSD_Knob_Heading, cockpit_device_id=devices.HSD, value_pressed=-0.01, value_up=0.0, name=_('Heading Knob [coarse] - CCW'), category=_('HSD')}, 
		{pressed=device_commands.HSD_Knob_Course, up=device_commands.HSD_Knob_Course, cockpit_device_id=devices.HSD, value_pressed=0.001, value_up=0.0, name=_('Course Knob [fine] - CW'), category=_('HSD')}, 
		{pressed=device_commands.HSD_Knob_Course, up=device_commands.HSD_Knob_Course, cockpit_device_id=devices.HSD, value_pressed=-0.001, value_up=0.0, name=_('Course Knob [fine] - CCW'), category=_('HSD')}, 
		{pressed=device_commands.HSD_Knob_Heading, up=device_commands.HSD_Knob_Heading, cockpit_device_id=devices.HSD, value_pressed=0.001, value_up=0.0, name=_('Heading Knob [fine] - CW'), category=_('HSD')}, 
		{pressed=device_commands.HSD_Knob_Heading, up=device_commands.HSD_Knob_Heading, cockpit_device_id=devices.HSD, value_pressed=-0.001, value_up=0.0, name=_('Heading Knob [fine] - CCW'), category=_('HSD')}, 
		{down=device_commands.HSD_Knob_Course, up=device_commands.HSD_Knob_Course, cockpit_device_id=devices.HSD, value_down=0.0028, value_up=0.0, name=_('Course Knob [+1°] - CW'), category=_('HSD')}, 
		{down=device_commands.HSD_Knob_Course, up=device_commands.HSD_Knob_Course, cockpit_device_id=devices.HSD, value_down=-0.0028, value_up=0.0, name=_('Course Knob [-1°] - CCW'), category=_('HSD')}, 
		{down=device_commands.HSD_Knob_Heading, up=device_commands.HSD_Knob_Heading, cockpit_device_id=devices.HSD, value_down=0.0028, value_up=0.0, name=_('Heading Knob [+1°] - CW'), category=_('HSD')}, 
		{down=device_commands.HSD_Knob_Heading, up=device_commands.HSD_Knob_Heading, cockpit_device_id=devices.HSD, value_down=-0.0028, value_up=0.0, name=_('Heading Knob [-1°] - CCW'), category=_('HSD')},

		{down=device_commands.HSD_Knob_Brightness, cockpit_device_id=devices.HSD, value_down=1.0, name=_('HSD Brightness Increase'), category=_('HSD')}, 
		{down=device_commands.HSD_Knob_Brightness, cockpit_device_id=devices.HSD, value_down=0.5, name=_('HSD Brightness Decrease'), category=_('HSD')},

		{down=device_commands.HSD_Btn_Test, up=device_commands.HSD_Btn_Test, cockpit_device_id=devices.HSD, value_down=1, value_up=0, name = _('HSD Test'), category = _('HSD')},

		{down = device_commands.SPOIL_Inboard_Override_Cover, 		cockpit_device_id = devices.ELECTRICS, value_down = 0, name = _('Inboard Spoiler Override Cover CLOSE'), category = { _('Spoilers')}},
		{down = device_commands.SPOIL_Inboard_Override_Cover, 		cockpit_device_id = devices.ELECTRICS, value_down = 1, name = _('Inboard Spoiler Override Cover OPEN'), category = { _('Spoilers')}},
		{down = device_commands.SPOIL_Outboard_Override_Cover, 		cockpit_device_id = devices.ELECTRICS, value_down = 0, name = _('Outboard Spoiler Override Cover CLOSE'), category = { _('Spoilers')}},
		{down = device_commands.SPOIL_Outboard_Override_Cover, 		cockpit_device_id = devices.ELECTRICS, value_down = 1, name = _('Outboard Spoiler Override Cover OPEN'), category = { _('Spoilers')}},
		{down = device_commands.SPOIL_Inboard_Override, 		cockpit_device_id = devices.ELECTRICS, value_down = 0, name = _('Inboard Spoiler Override NORM'), category = { _('Spoilers')}},
		{down = device_commands.SPOIL_Inboard_Override, 		cockpit_device_id = devices.ELECTRICS, value_down = 1, name = _('Inboard Spoiler Override ORIDE'), category = { _('Spoilers')}},
		{down = device_commands.SPOIL_Outboard_Override, 		cockpit_device_id = devices.ELECTRICS, value_down = 0, name = _('Outboard Spoiler Override NORM'), category = { _('Spoilers')}},
		{down = device_commands.SPOIL_Outboard_Override, 		cockpit_device_id = devices.ELECTRICS, value_down = 1, name = _('Outboard Spoiler Override ORIDE'), category = { _('Spoilers')}},

		{down = device_commands.WEAP_Gun_Ammo_adjust, 		cockpit_device_id = devices.WEAPONS, value_down = -0.1, name = _('Gun Ammunition Counter Adjustment Decrease'), category = { _('PDCP')}},
		{down = device_commands.WEAP_Gun_Ammo_adjust, 		cockpit_device_id = devices.WEAPONS, value_down = 0.1, name = _('Gun Ammunition Counter Adjustment Increase'), category = { _('PDCP')}},

		{down = device_commands.WEAP_Gun_Elevation, 		cockpit_device_id = devices.WEAPONS, value_down = 0.5, name = _('Gun Elevation Lead Adjustment Decrease'), category = { _('PDCP')}},
		{down = device_commands.WEAP_Gun_Elevation, 		cockpit_device_id = devices.WEAPONS, value_down = 1.0, name = _('Gun Elevation Lead Adjustment Increase'), category = { _('PDCP')}},

		{down = device_commands.TID_VideoExportToggle, cockpit_device_id = devices.TID, value_down = 1, name = _('Video Export Toggle'), category = _('Other')},	

{ down = device_commands.HCU_key_updown, up = device_commands.HCU_key_updown, value_down = 1, value_up = 0, cockpit_device_id=devices.HCU, name = _('HCU forward'), category = _('Jester BRG - HCU')},
{ down = device_commands.HCU_key_updown, up = device_commands.HCU_key_updown, value_down = -1, value_up = 0, cockpit_device_id=devices.HCU, name = _('HCU backward'), category = _('Jester BRG - HCU')},
{ down = device_commands.HCU_key_leftright, up = device_commands.HCU_key_leftright, value_down = -1, value_up = 0, cockpit_device_id=devices.HCU, name = _('HCU Left'), category = _('Jester BRG - HCU')},
{ down = device_commands.HCU_key_leftright, up = device_commands.HCU_key_leftright, value_down = 1, value_up = 0, cockpit_device_id=devices.HCU, name = _('HCU Right'), category = _('Jester BRG - HCU')},
{ down = device_commands.HCU_key_center, value_down = 1, cockpit_device_id=devices.HCU, name = _('HCU Center'), category = _('Jester BRG - HCU')},
{ down = device_commands.HCU_halfaction, up = device_commands.HCU_halfaction, value_down = 1, value_up = 0, cockpit_device_id=devices.HCU, name = _('HCU half-action'), category = _('Jester BRG - HCU')},
{ down = device_commands.HCU_fullaction, up = device_commands.HCU_fullaction, value_down = 1, value_up = 0, cockpit_device_id=devices.HCU, name = _('HCU full-action'), category = _('Jester BRG - HCU')},
{ up=device_commands.HCU_IR_TV, down=device_commands.HCU_IR_TV, cockpit_device_id=devices.HCU, value_up=0.0, value_down=1.0, 	name=_('HCU TCS mode'),	 category=_('Jester BRG - HCU')},
{ up=device_commands.HCU_RDR, down=device_commands.HCU_RDR, cockpit_device_id=devices.HCU, value_up=0.0, value_down=1.0, 	name=_('HCU radar mode'),	 category=_('Jester BRG - HCU')},
{ up=device_commands.HCU_DDD_cursor, down=device_commands.HCU_DDD_cursor, cockpit_device_id=devices.HCU, value_up=0.0, value_down=1.0, 	name=_('HCU DDD mode'),	 category=_('Jester BRG - HCU')},
{ up=device_commands.HCU_TID_cursor, down=device_commands.HCU_TID_cursor, cockpit_device_id=devices.HCU, value_up=0.0, value_down=1.0, 	name=_('HCU TID mode'),	 category=_('Jester BRG - HCU')},

{down = device_commands.TID_mode_knob, cockpit_device_id=devices.TID, value_down = 0, name = _('TID Mode: GND STAB'), category = _('Jester BRG - TID')},
{down = device_commands.TID_mode_knob, cockpit_device_id=devices.TID, value_down = 0.3333, name = _('TID Mode: AC STAB'), category = _('Jester BRG - TID')},
{down = device_commands.TID_mode_knob, cockpit_device_id=devices.TID, value_down = 0.6666, name = _('TID Mode: ATTK'), category = _('Jester BRG - TID')},
{down = device_commands.TID_mode_knob, cockpit_device_id=devices.TID, value_down = 1.0, name = _('TID Mode: TV'), category = _('Jester BRG - TID')},

{down = device_commands.TID_range_knob, cockpit_device_id=devices.TID, value_down = -1.0, name = _('TID range: 25'), category = _('Jester BRG - TID')},
{down = device_commands.TID_range_knob, cockpit_device_id=devices.TID, value_down = -0.5, name = _('TID range: 50'), category = _('Jester BRG - TID')},
{down = device_commands.TID_range_knob, cockpit_device_id=devices.TID, value_down = 0.0, name = _('TID range: 100'), category = _('Jester BRG - TID')},
{down = device_commands.TID_range_knob, cockpit_device_id=devices.TID, value_down = 0.5, name = _('TID range: 200'), category = _('Jester BRG - TID')},
{down = device_commands.TID_range_knob, cockpit_device_id=devices.TID, value_down = 1.0, name = _('TID range: 400'), category = _('Jester BRG - TID')},

{cockpit_device_id=devices.TID, down = device_commands.TID_NON_ATTK, value_down = 1, up = device_commands.TID_NON_ATTK, value_up = 0, name = _('TID Symbology: Non Attack'), category = _('Jester BRG - TID')},
{cockpit_device_id=devices.TID, down = device_commands.TID_DATA_LINK, value_down = 1, up = device_commands.TID_DATA_LINK, value_up = 0, name = _('TID Symbology: Data Link'), category = _('Jester BRG - TID')},
{cockpit_device_id=devices.TID, down = device_commands.TID_JAM_STROBE, value_down = 1, up = device_commands.TID_JAM_STROBE, value_up = 0, name = _('TID Symbology: Jam Strobe'), category = _('Jester BRG - TID')},
{cockpit_device_id=devices.TID, down = device_commands.TID_SYM_ELEM, value_down = 1, up = device_commands.TID_SYM_ELEM, value_up = 0, name = _('TID Symbology: Sym Elem'), category = _('Jester BRG - TID')},
{cockpit_device_id=devices.TID, down = device_commands.TID_ALT_NUM, value_down = 1, up = device_commands.TID_ALT_NUM, value_up = 0, name = _('TID Symbology: Alt Num'), category = _('Jester BRG - TID')},
{cockpit_device_id=devices.TID, down = device_commands.TID_RID_DSBL, value_down = 1, up = device_commands.TID_RID_DSBL, value_up = 0, name = _('TID Symbology: RID DSBL'), category = _('Jester BRG - TID')},
{cockpit_device_id=devices.TID, down = device_commands.TID_LAUNCH_ZONE, value_down = 1, up = device_commands.TID_LAUNCH_ZONE, value_up = 0, name = _('TID Symbology: Launch Zone'), category = _('Jester BRG - TID')},
{cockpit_device_id=devices.TID, down = device_commands.TID_VEL_VECTOR, value_down = 1, up = device_commands.TID_VEL_VECTOR, value_up = 0, name = _('TID Symbology: Vel Vector'), category = _('Jester BRG - TID')},
{cockpit_device_id=devices.TID, down = device_commands.TID_CLSN, value_down = 1, up = device_commands.TID_CLSN, value_up = 0, name = _('TID CLSN'), category = _('Jester BRG - TID')},
{cockpit_device_id=devices.TID, down = device_commands.TID_trackhold, value_down = 1, up = device_commands.TID_trackhold, value_up = 0, name = _('TID Trackhold'), category = _('Jester BRG - TID')},

{down = device_commands.TID_dest_mode, cockpit_device_id=devices.NAV_INTERFACE, value_down = 0, name = _('TID Destination: 1'), category = _('Jester BRG - TID')},
{down = device_commands.TID_dest_mode, cockpit_device_id=devices.NAV_INTERFACE, value_down = 0.142857, name = _('TID Destination: 2'), category = _('Jester BRG - TID')},
{down = device_commands.TID_dest_mode, cockpit_device_id=devices.NAV_INTERFACE, value_down = 0.285714, name = _('TID Destination: 3'), category = _('Jester BRG - TID')},
{down = device_commands.TID_dest_mode, cockpit_device_id=devices.NAV_INTERFACE, value_down = 0.428571, name = _('TID Destination: FP'), category = _('Jester BRG - TID')},
{down = device_commands.TID_dest_mode, cockpit_device_id=devices.NAV_INTERFACE, value_down = 0.571428, name = _('TID Destination: IP'), category = _('Jester BRG - TID')},
{down = device_commands.TID_dest_mode, cockpit_device_id=devices.NAV_INTERFACE, value_down = 0.714285, name = _('TID Destination: ST'), category = _('Jester BRG - TID')},
{down = device_commands.TID_dest_mode, cockpit_device_id=devices.NAV_INTERFACE, value_down = 0.857142, name = _('TID Destination: HB'), category = _('Jester BRG - TID')},
{down = device_commands.TID_dest_mode, cockpit_device_id=devices.NAV_INTERFACE, value_down = 1.0, name = _('TID Destination: MAN'), category = _('Jester BRG - TID')},

{down = device_commands.RADAR_DDD_MLC, cockpit_device_id=devices.RADAR, value_down = -1, name = _('MLC out'), category = _('Jester BRG - RCP')},
{down = device_commands.RADAR_DDD_MLC, cockpit_device_id=devices.RADAR, value_down = 0, name = _('MLC auto'), category = _('Jester BRG - RCP')},
{down = device_commands.RADAR_DDD_MLC, cockpit_device_id=devices.RADAR, value_down = 1, name = _('MLC in'), category = _('Jester BRG - RCP')},

{ down = device_commands.RADAR_elevation_bars_change, cockpit_device_id=devices.RADAR, value_down = 1, name = _('Radar elevation bars increase'), category = _('Jester BRG - RCP')},
{ down = device_commands.RADAR_elevation_bars_change, cockpit_device_id=devices.RADAR, value_down = -1, name = _('Radar elevation bars decrease'), category = _('Jester BRG - RCP')},
{ down = device_commands.RADAR_azimuth_scan_change, cockpit_device_id=devices.RADAR, value_down = 1, name = _('Radar azimuth scan wider'), category = _('Jester BRG - RCP')},
{ down = device_commands.RADAR_azimuth_scan_change, cockpit_device_id=devices.RADAR, value_down = -1, name = _('Radar azimuth scan narrower'), category = _('Jester BRG - RCP')},
{ up = device_commands.RADAR_elevation_updown, down = device_commands.RADAR_elevation_updown, cockpit_device_id=devices.RADAR, value_down = 1, value_up = 0, name = _('Radar elevation up'), category = _('Jester BRG - RCP')},
{ up = device_commands.RADAR_elevation_updown, down = device_commands.RADAR_elevation_updown, cockpit_device_id=devices.RADAR, value_down = -1, value_up = 0, name = _('Radar elevation down'), category = _('Jester BRG - RCP')},
{ up = device_commands.RADAR_azimuth_leftright, down = device_commands.RADAR_azimuth_leftright, cockpit_device_id=devices.RADAR, value_down = 1, value_up = 0, name = _('Radar azimuth right'), category = _('Jester BRG - RCP')},
{ up = device_commands.RADAR_azimuth_leftright, down = device_commands.RADAR_azimuth_leftright, cockpit_device_id=devices.RADAR, value_down = -1, value_up = 0, name = _('Radar azimuth left'), category = _('Jester BRG - RCP')},
{ up = device_commands.RADAR_elevation_center, down = device_commands.RADAR_elevation_center, cockpit_device_id=devices.RADAR, value_down = 1, value_up = 0, name = _('Radar elevation re-center'), category = _('Jester BRG - RCP')},
{ up = device_commands.RADAR_azimuth_center, down = device_commands.RADAR_azimuth_center, cockpit_device_id=devices.RADAR, value_down = 1, value_up = 0, name = _('Radar azimuth re-center'), category = _('Jester BRG - RCP')},

{ cockpit_device_id=devices.RADAR, down = device_commands.RADAR_DDD_WCS_PSRCH,   value_down = 1, up = device_commands.RADAR_DDD_WCS_PSRCH,   value_up = 0, name = _('RADAR Pulse Search'), category = _('Jester BRG - RCP')},
{ cockpit_device_id=devices.RADAR, down = device_commands.RADAR_DDD_WCS_TWSMAN,  value_down = 1, up = device_commands.RADAR_DDD_WCS_TWSMAN,  value_up = 0, name = _('RADAR Track While Scan manual'), category = _('Jester BRG - RCP')},
{ cockpit_device_id=devices.RADAR, down = device_commands.RADAR_DDD_WCS_TWSAUTO, value_down = 1, up = device_commands.RADAR_DDD_WCS_TWSAUTO, value_up = 0, name = _('RADAR Track While Scan auto'), category = _('Jester BRG - RCP')},
{ cockpit_device_id=devices.RADAR, down = device_commands.RADAR_DDD_WCS_RWS,     value_down = 1, up = device_commands.RADAR_DDD_WCS_RWS,     value_up = 0, name = _('RADAR Range While Scan'), category = _('Jester BRG - RCP')},
{ cockpit_device_id=devices.RADAR, down = device_commands.RADAR_DDD_WCS_PDSRCH,  value_down = 1, up = device_commands.RADAR_DDD_WCS_PDSRCH,  value_up = 0, name = _('RADAR Pulse Doppler Search'), category = _('Jester BRG - RCP')},
{ cockpit_device_id=devices.RADAR, down = device_commands.RADAR_DDD_WCS_PSTT,    value_down = 1, up = device_commands.RADAR_DDD_WCS_PSTT,    value_up = 0, name = _('RADAR Pulse Single Target Track'), category = _('Jester BRG - RCP')},
{ cockpit_device_id=devices.RADAR, down = device_commands.RADAR_DDD_WCS_PDSTT,   value_down = 1, up = device_commands.RADAR_DDD_WCS_PDSTT,   value_up = 0, name = _('RADAR Pulse Doppler Single Target Track'), category = _('Jester BRG - RCP')},
{ cockpit_device_id=devices.RADAR, down = device_commands.RADAR_DDD_display_IFF, value_down = 1, up = device_commands.RADAR_DDD_display_IFF, value_up = 0, name = _('DDD Interrogate Friend or Foe'), category = _('Jester BRG - RCP')},

{ cockpit_device_id=devices.RADAR, down = device_commands.RADAR_VSL_switch, value_down = 1, up = device_commands.RADAR_VSL_switch, value_up = 0, name = _('VSL High'), category = _('Jester BRG - RCP')},
{ cockpit_device_id=devices.RADAR, down = device_commands.RADAR_VSL_switch, value_down = -1, up = device_commands.RADAR_VSL_switch, value_up = 0, name = _('VSL Low'), category = _('Jester BRG - RCP')},
{down = device_commands.HCU_WCS_enable,  up = device_commands.HCU_WCS_enable, cockpit_device_id=devices.RADAR, value_down = 1, value_up = 0, name = _('WCS XMIT, else Standby'), category = _('Jester BRG - RCP')},
{down = device_commands.HCU_WCS_enable,  up = device_commands.HCU_WCS_enable, cockpit_device_id=devices.RADAR, value_down = -1, value_up = 0, name = _('WCS Off, else Standby'), category = _('Jester BRG - RCP')},
{down = device_commands.HCU_WCS_enable, cockpit_device_id=devices.RADAR, value_down = 1, name = _('WCS XMIT'), category = _('Jester BRG - RCP')},
{down = device_commands.HCU_WCS_enable, cockpit_device_id=devices.RADAR, value_down = 0, name = _('WCS Standby'), category = _('Jester BRG - RCP')},
{down = device_commands.HCU_WCS_enable, cockpit_device_id=devices.RADAR, value_down = -1, name = _('WCS Off'), category = _('Jester BRG - RCP')},


{down = device_commands.RWR_DISPLAY_MODE, up = device_commands.RWR_DISPLAY_MODE, cockpit_device_id=devices.RWR, value_down = 1, value_up = 0, name = _('RWR Display Mode OFST'), category = _('Jester BRG - RWR')},
{down = device_commands.RWR_DISPLAY_MODE, up = device_commands.RWR_DISPLAY_MODE, cockpit_device_id=devices.RWR, value_down = -1, value_up = 0, name = _('RWR Display Mode LMT'), category = _('Jester BRG - RWR')},

{down = device_commands.CMDS_RIO_Left_Grip_Hat_V, up = device_commands.CMDS_RIO_Left_Grip_Hat_V, cockpit_device_id = devices.COUNTERMEASURES, value_down = 1, value_up = 0, name = _('AN/ALE-39 Left Data Dispenser Switch Up - Chaff Single'), category = _('Jester BRG - CMS')},
{down = device_commands.CMDS_RIO_Left_Grip_Hat_H, up = device_commands.CMDS_RIO_Left_Grip_Hat_H, cockpit_device_id = devices.COUNTERMEASURES, value_down = -1, value_up = 0, name = _('AN/ALE-39 Left Data Dispenser Switch Left - Flare Program'), category = _('Jester BRG - CMS')},
{down = device_commands.CMDS_RIO_Left_Grip_Hat_V, up = device_commands.CMDS_RIO_Left_Grip_Hat_V, cockpit_device_id = devices.COUNTERMEASURES, value_down = -1, value_up = 0, name = _('AN/ALE-39 Left Data Dispenser Switch Down - Chaff Program'), category = _('Jester BRG - CMS')},
{down = device_commands.CMDS_RIO_Left_Grip_Hat_H, up = device_commands.CMDS_RIO_Left_Grip_Hat_H, cockpit_device_id = devices.COUNTERMEASURES, value_down = 1, value_up = 0, name = _('AN/ALE-39 Left Data Dispenser Switch Right - Jammer Program'), category = _('Jester BRG - CMS')},
{down = device_commands.CMDS_RIO_Right_Grip_Hat_V, up = device_commands.CMDS_RIO_Right_Grip_Hat_V, cockpit_device_id = devices.COUNTERMEASURES, value_down = 1, value_up = 0, name = _('AN/ALE-39 Right Data Dispenser Switch Up - Chaff Single'), category = _('Jester BRG - CMS')},
{down = device_commands.CMDS_RIO_Right_Grip_Hat_H, up = device_commands.CMDS_RIO_Right_Grip_Hat_H, cockpit_device_id = devices.COUNTERMEASURES, value_down = 1, value_up = 0, name = _('AN/ALE-39 Right Data Dispenser Switch Right - Flare Program'), category = _('Jester BRG - CMS')},
{down = device_commands.CMDS_RIO_Right_Grip_Hat_V, up = device_commands.CMDS_RIO_Right_Grip_Hat_V, cockpit_device_id = devices.COUNTERMEASURES, value_down = -1, value_up = 0, name = _('AN/ALE-39 Right Data Dispenser Switch Down - Chaff Program'), category = _('Jester BRG - CMS')},
{down = device_commands.CMDS_RIO_Right_Grip_Hat_H, up = device_commands.CMDS_RIO_Right_Grip_Hat_H, cockpit_device_id = devices.COUNTERMEASURES, value_down = -1, value_up = 0, name = _('AN/ALE-39 Right Data Dispenser Switch Left - Jammer Program'), category = _('Jester BRG - CMS')},

{cockpit_device_id=devices.TID, down = device_commands.WEAP_Next_launch, value_down = 1, up = device_commands.WEAP_Next_launch, value_up = 0, name = _('Next launch'), category = _('Jester BRG - Weapons')},

--************** Computer Address Panel ******************8
{down = device_commands.CAP_BRG_0, up = device_commands.CAP_BRG_0, value_down = 1, value_up = 0, cockpit_device_id=devices.CAP, name = _('CAP 0/Bearing'), category = _('Jester BRG - CAP')},
{down = device_commands.CAP_LAT_1, up = device_commands.CAP_LAT_1, value_down = 1, value_up = 0, cockpit_device_id=devices.CAP, name = _('CAP 1/Latitude'), category = _('Jester BRG - CAP')},
{down = device_commands.CAP_NBR_2, up = device_commands.CAP_NBR_2, value_down = 1, value_up = 0, cockpit_device_id=devices.CAP, name = _('CAP 2/Number'), category = _('Jester BRG - CAP')},
{down = device_commands.CAP_SPD_3, up = device_commands.CAP_SPD_3, value_down = 1, value_up = 0, cockpit_device_id=devices.CAP, name = _('CAP 3/Speed'), category = _('Jester BRG - CAP')},
{down = device_commands.CAP_ALT_4, up = device_commands.CAP_ALT_4, value_down = 1, value_up = 0, cockpit_device_id=devices.CAP, name = _('CAP 4/Altitude'), category = _('Jester BRG - CAP')},
{down = device_commands.CAP_RNG_5, up = device_commands.CAP_RNG_5, value_down = 1, value_up = 0, cockpit_device_id=devices.CAP, name = _('CAP 5/Range'), category = _('Jester BRG - CAP')},
{down = device_commands.CAP_LONG_6,up = device_commands.CAP_LONG_6, value_down = 1, value_up = 0, cockpit_device_id=devices.CAP, name = _('CAP 6/Longitude'), category = _('Jester BRG - CAP')},
{down = device_commands.CAP_7,     up = device_commands.CAP_7, value_down = 1, value_up = 0, cockpit_device_id=devices.CAP, name = _('CAP 7'), category = _('Jester BRG - CAP')},
{down = device_commands.CAP_HDG_8, up = device_commands.CAP_HDG_8, value_down = 1, value_up = 0, cockpit_device_id=devices.CAP, name = _('CAP 8/Heading'), category = _('Jester BRG - CAP')},
{down = device_commands.CAP_9,     up = device_commands.CAP_9, value_down = 1, value_up = 0, cockpit_device_id=devices.CAP, name = _('CAP 9'), category = _('Jester BRG - CAP')},

{down = device_commands.CAP_enter,     up = device_commands.CAP_enter, value_down = 1, value_up = 0, cockpit_device_id=devices.CAP, name = _('CAP Enter'), category = _('Jester BRG - CAP')},
{down = device_commands.CAP_clear,     up = device_commands.CAP_clear, value_down = 1, value_up = 0, cockpit_device_id=devices.CAP, name = _('CAP Clear'), category = _('Jester BRG - CAP')},
{down = device_commands.CAP_NE,     up = device_commands.CAP_NE, value_down = 1, value_up = 0, cockpit_device_id=devices.CAP, name = _('CAP N/E/+'), category = _('Jester BRG - CAP')},
{down = device_commands.CAP_SW,     up = device_commands.CAP_SW, value_down = 1, value_up = 0, cockpit_device_id=devices.CAP, name = _('CAP S/W/-'), category = _('Jester BRG - CAP')},

{down = device_commands.CAP_button1, up = device_commands.CAP_button1, value_down = 1, value_up = 0, cockpit_device_id=devices.CAP, name = _('CAP button 1'), category = _('Jester BRG - CAP')},
{down = device_commands.CAP_button2, up = device_commands.CAP_button2, value_down = 1, value_up = 0, cockpit_device_id=devices.CAP, name = _('CAP button 2'), category = _('Jester BRG - CAP')},
{down = device_commands.CAP_button3, up = device_commands.CAP_button3, value_down = 1, value_up = 0, cockpit_device_id=devices.CAP, name = _('CAP button 3'), category = _('Jester BRG - CAP')},
{down = device_commands.CAP_button4, up = device_commands.CAP_button4, value_down = 1, value_up = 0, cockpit_device_id=devices.CAP, name = _('CAP button 4'), category = _('Jester BRG - CAP')},
{down = device_commands.CAP_button5, up = device_commands.CAP_button5, value_down = 1, value_up = 0, cockpit_device_id=devices.CAP, name = _('CAP button 5'), category = _('Jester BRG - CAP')},
{down = device_commands.CAP_button6, up = device_commands.CAP_button6, value_down = 1, value_up = 0, cockpit_device_id=devices.CAP, name = _('CAP button 6 - FND/TACAN FIX'), category = _('Jester BRG - CAP')},
{down = device_commands.CAP_button7, up = device_commands.CAP_button7, value_down = 1, value_up = 0, cockpit_device_id=devices.CAP, name = _('CAP button 7 - UNK'), category = _('Jester BRG - CAP')},
{down = device_commands.CAP_button8, up = device_commands.CAP_button8, value_down = 1, value_up = 0, cockpit_device_id=devices.CAP, name = _('CAP button 8 - HOST'), category = _('Jester BRG - CAP')},
{down = device_commands.CAP_button9, up = device_commands.CAP_button9, value_down = 1, value_up = 0, cockpit_device_id=devices.CAP, name = _('CAP button 9 - FIX ENABLE'), category = _('Jester BRG - CAP')},
{down = device_commands.CAP_button10, up = device_commands.CAP_button10, value_down = 1, value_up = 0, cockpit_device_id=devices.CAP, name = _('CAP button 10'), category = _('Jester BRG - CAP')},

{down = device_commands.CAP_program_restart, up = device_commands.CAP_program_restart, value_down = 1, value_up = 0, cockpit_device_id=devices.CAP, name = _('CAP program restart'), category = _('Jester BRG - CAP')},

{down = device_commands.CAP_category, cockpit_device_id=devices.CAP, value_down = 0, name=_('CAP category BIT'), category=_('Jester BRG - CAP')},
{down = device_commands.CAP_category, cockpit_device_id=devices.CAP, value_down = 0.2, name=_('CAP category SPL'), category=_('Jester BRG - CAP')},
{down = device_commands.CAP_category, cockpit_device_id=devices.CAP, value_down = 0.4, name=_('CAP category NAV'), category=_('Jester BRG - CAP')},
{down = device_commands.CAP_category, cockpit_device_id=devices.CAP, value_down = 0.6, name=_('CAP category TAC'), category=_('Jester BRG - CAP')},
{down = device_commands.CAP_category, cockpit_device_id=devices.CAP, value_down = 0.8, name=_('CAP category D/L'), category=_('Jester BRG - CAP')},
{down = device_commands.CAP_category, cockpit_device_id=devices.CAP, value_down = 1.0, name=_('CAP category TGT'), category=_('Jester BRG - CAP')},
{down = device_commands.CAP_category_cw, cockpit_device_id=devices.CAP, value_down = 1.0, name=_('CAP category turn CW'), category=_('Jester BRG - CAP')},
{down = device_commands.CAP_category_ccw, cockpit_device_id=devices.CAP, value_down = 1.0, name=_('CAP category turn CCW'), category=_('Jester BRG - CAP')},


{	cockpit_device_id=devices.LANTIRN, down=device_commands.LANTIRN_XAxisKey, up=device_commands.LANTIRN_XAxisKey, value_down=1.0,	value_up=0.0, name=_('LANTIRN Slew Right'), category=_('Jester BRG - LANTIRN')},
{	cockpit_device_id=devices.LANTIRN, down=device_commands.LANTIRN_XAxisKey, up=device_commands.LANTIRN_XAxisKey, value_down=-1.0,	value_up=0.0, name=_('LANTIRN Slew Left'), category=_('Jester BRG - LANTIRN')},
{	cockpit_device_id=devices.LANTIRN, down=device_commands.LANTIRN_YAxisKey, up=device_commands.LANTIRN_YAxisKey, value_down=1.0,	value_up=0.0, name=_('LANTIRN Slew Up'), category=_('Jester BRG - LANTIRN')},
{	cockpit_device_id=devices.LANTIRN, down=device_commands.LANTIRN_YAxisKey, up=device_commands.LANTIRN_YAxisKey, value_down=-1.0,	value_up=0.0, name=_('LANTIRN Slew Down'), category=_('Jester BRG - LANTIRN')},
{	cockpit_device_id=devices.LANTIRN, down=device_commands.LANTIRN_TriggerHalf, up=device_commands.LANTIRN_TriggerHalf, value_down=1.0,	value_up=0.0, name=_('LANTIRN Trigger Half Action'), category=_('Jester BRG - LANTIRN')},
{	cockpit_device_id=devices.LANTIRN, down=device_commands.LANTIRN_TriggerFull, up=device_commands.LANTIRN_TriggerFull, value_down=1.0,	value_up=0.0, name=_('LANTIRN Trigger Full Action'), category=_('Jester BRG - LANTIRN')},
{	cockpit_device_id=devices.LANTIRN, down=device_commands.LANTIRN_LaserLatched, value_down=1.0,	value_up=0.0, name=_('LANTIRN Laser Latched'), category=_('Jester BRG - LANTIRN')},
{	cockpit_device_id=devices.LANTIRN, down=device_commands.LANTIRN_Undesignate, value_down=1.0,	value_up=0.0, name=_('LANTIRN Undesignate'), category=_('Jester BRG - LANTIRN')},
{	cockpit_device_id=devices.LANTIRN, down=device_commands.LANTIRN_ToggleFOV, value_down=1.0, value_up = 0.0, name=_('LANTIRN Toggle FOV'), category=_('Jester BRG - LANTIRN')},
{	cockpit_device_id=devices.LANTIRN, down=device_commands.LANTIRN_PointTrack, up=device_commands.LANTIRN_PointTrack, value_down=1.0,	value_up=0.0, name=_('LANTIRN Point Track'), category=_('Jester BRG - LANTIRN')},
{	cockpit_device_id=devices.LANTIRN, down=device_commands.LANTIRN_AreaTrack, up=device_commands.LANTIRN_AreaTrack, value_down=1.0,	value_up=0.0, name=_('LANTIRN Area Track'), category=_('Jester BRG - LANTIRN')},
{	cockpit_device_id=devices.LANTIRN, down=device_commands.LANTIRN_QHUD_QADL, up=device_commands.LANTIRN_QHUD_QADL,value_down=1.0,	value_up=0.0, name=_('LANTIRN S4 HAT Up (QADL/QHUD/Code +/Gain+)'), category=_('Jester BRG - LANTIRN')},
{	cockpit_device_id=devices.LANTIRN, down=device_commands.LANTIRN_QDES, up=device_commands.LANTIRN_QDES, value_down=1.0,	value_up=0.0, name=_('LANTIRN S4 HAT Right (QDES/Digit Right/Level+)'), category=_('Jester BRG - LANTIRN')},
{	cockpit_device_id=devices.LANTIRN, down=device_commands.LANTIRN_QSNO, up=device_commands.LANTIRN_QSNO, value_down=1.0,	value_up=0.0, name=_('LANTIRN S4 HAT Down (QSNO/Code -/Gain-)'), category=_('Jester BRG - LANTIRN')},
{	cockpit_device_id=devices.LANTIRN, down=device_commands.LANTIRN_QHATLeft, up=device_commands.LANTIRN_QHATLeft, value_down=1.0,	value_up=0.0, name=_('LANTIRN S4 HAT Left (Digit Left/Level-)'), category=_('Jester BRG - LANTIRN')},
{	cockpit_device_id=devices.LANTIRN, down=device_commands.LANTIRN_GPSZero, up=device_commands.LANTIRN_GPSZero, value_down=1.0,	value_up=0.0, name=_('LANTIRN S4 HAT Press (Declutter/Lase Auto-Man/MGC)'), category=_('Jester BRG - LANTIRN')},
{	cockpit_device_id=devices.LANTIRN, down=device_commands.LANTIRN_QWP_Minus, value_down=1.0, name=_('LANTIRN QWP-'), category=_('Jester BRG - LANTIRN')},
{	cockpit_device_id=devices.LANTIRN, down=device_commands.LANTIRN_QWP_Plus, value_down=1.0, name=_('LANTIRN QWP+'), category=_('Jester BRG - LANTIRN')},
{	cockpit_device_id=devices.LANTIRN, down=device_commands.LANTIRN_Laser_ARM_Toggle, value_down=1.0, name=_('LANTIRN Laser Arm Toggle'), category=_('Jester BRG - LANTIRN')},
{	cockpit_device_id=devices.LANTIRN, down=device_commands.LANTIRN_Laser_ARM, value_down=1.0,name=_('LANTIRN Laser Arm ARM'), category=_('Jester BRG - LANTIRN')},
{	cockpit_device_id=devices.LANTIRN, down=device_commands.LANTIRN_Laser_ARM, value_down=0.0, name=_('LANTIRN Laser Arm SAFE'), category=_('Jester BRG - LANTIRN')},
{	cockpit_device_id=devices.LANTIRN, down=device_commands.LANTIRN_ToggleWHOTBHOT, up=device_commands.LANTIRN_ToggleWHOTBHOT, value_down=1.0,	value_up=0.0, name=_('LANTIRN Toggle WHOT / BHOT'), category=_('Jester BRG - LANTIRN')},
{	cockpit_device_id=devices.LANTIRN, down=device_commands.LANTIRN_S1Slider, up=device_commands.LANTIRN_S1Slider, value_down=1.0, value_up = 0, name=_('LANTIRN Slider AGC/MGC'), category=_('Jester BRG - LANTIRN')},
{	cockpit_device_id=devices.LANTIRN, down=device_commands.LANTIRN_S1Slider, up=device_commands.LANTIRN_S1Slider, value_down=-1.0, value_up = 0, name=_('LANTIRN Slider Laser/Focus'), category=_('Jester BRG - LANTIRN')},
{	cockpit_device_id=devices.LANTIRN, down=device_commands.LANTIRN_MasterMode, value_down=0.0,	name=_('LANTIRN Mode NAV - A/A '), category=_('Jester BRG - LANTIRN')},
{	cockpit_device_id=devices.LANTIRN, down=device_commands.LANTIRN_MasterMode, value_down=1.0,	name=_('LANTIRN Mode A/G'), category=_('Jester BRG - LANTIRN')},
{	cockpit_device_id=devices.LANTIRN, down=device_commands.LANTIRN_MasterModeToggle, value_down=1.0,	name=_('LANTIRN Mode Toggle'), category=_('Jester BRG - LANTIRN')},
{	cockpit_device_id=devices.LANTIRN, down=device_commands.LANTIRN_PowerMode, value_down=0.0,	name=_('LANTIRN Power OFF'), category=_('Jester BRG - LANTIRN')},
{	cockpit_device_id=devices.LANTIRN, down=device_commands.LANTIRN_PowerMode, value_down=0.5,	name=_('LANTIRN Power IMU'), category=_('Jester BRG - LANTIRN')},
{	cockpit_device_id=devices.LANTIRN, down=device_commands.LANTIRN_PowerMode, value_down=1.0,	name=_('LANTIRN Power POD'), category=_('Jester BRG - LANTIRN')},
{	cockpit_device_id=devices.LANTIRN, down=device_commands.LANTIRN_PowerMode_Toggle, value_down=1.0, value_up=0.0, name=_('LANTIRN Power Toggle'), category=_('Jester BRG - LANTIRN')},
{	cockpit_device_id=devices.LANTIRN, down=device_commands.LANTIRN_OPER_STBY_Toggle, value_down=1.0, value_up=0.0, name=_('LANTIRN OPER / STBY (Unstow)'), category=_('Jester BRG - LANTIRN')},
	}
}